### ISSUE TITLE
请问博主文章原文有吗

### ISSUE THREAD

**Issue by cheeenzq** [Ye-zixiao/Double-YOLO-Kaist#1]
请问博主文章原文有吗，我在网络上搜不到

**Comment by Ye-zixiao** [comment]
哪个原文？

**Comment by cheeenzq** [comment]
> ###
不好意思刚刚没引用，是这一篇：一种基于YOLOv3/4的混合模态行人检测算法

**Comment by Ye-zixiao** [comment]
我没发，感觉自己的工作不咋地😂，别人应该有类似的工作了，你可以找找。

**Comment by cheeenzq** [comment]
> 我想做一个yolov5的网络双通道网络，然后搜了很久没搜到关于这个的，然后搜到了博主你的代码，感觉文章和我想法很想很想，就想取取经。

**Comment by Ye-zixiao** [comment]
先加我微信（1461018824）吧，晚上或者周末聊吧，我现在在公司😂。

**Comment by cheeenzq** [comment]
好的好的，十分感谢了。
