### ISSUE TITLE
数据集下载后文件解压出错

### ISSUE THREAD

**Issue by zyfone** [Ye-zixiao/Double-YOLO-Kaist#2]
您好，感谢提供的开源项目
我想使用一下该项目的数据集完成其他研究
但是我通过百度云链接下载数据压缩包后
除了001其他的压缩包都显示损坏无法解压

**Comment by Ye-zixiao** [comment]
我晚上下班了给你看下😢。

**Comment by zyfone** [comment]
非常感谢

**Comment by Ye-zixiao** [comment]
你没用对吧，这几个压缩包要一起下载下来，然后解压。你不会是只单独下载了一个文件别的文件没有下载下来吧？或者是先下了一个解压，然后再下下一个？我随便把原始的数据（没有清洗过）都给你，你拿去自己倒腾都可以：链接: https://pan.baidu.com/s/1J3qcBTPRIXN6-ydVVMxw7A?pwd=223f 提取码: 223f。

**Comment by zyfone** [comment]
哦哦哦，萌新不太懂，
我就是全下载下来的发现只有001可以解压缩，
其他的不可以，我还以为少了文件
实在是不好意思蛤

**Comment by Ye-zixiao** [comment]
这个你自己解决，真不行你就用那个原始数据，写一个python脚本生成一些新的数据就可以了，使用原始数据没有必要且非常耗费时间。

**Comment by zyfone** [comment]
okok，感谢帮助
