### ISSUE TITLE
无法复现测试结果精度

### ISSUE THREAD

**Issue by QRvlS** [Ye-zixiao/Double-YOLO-Kaist#4]
大大再求教一下！在训练kaist_dyolov3_fshare_global_concat_se3.cfg这个模型的时候，自己训练的AP和LAMR数值无法达到给定的数值，求教一下大大如何训练才能达到近90%的AP率，是我训练错了模型还是哪个参数需要修改，麻烦大大了！
【train.py参数设置】
![1678534202893](https://user-images.githubusercontent.com/119500043/224481868-6389c968-3687-40c0-aab4-d15c90b94ee4.png)
【evaluate.py参数设置】
![1678534227834](https://user-images.githubusercontent.com/119500043/224481884-7c83d6d4-f67a-4d81-9143-2428fdcbb57f.png)
【训练出的精度，AP在70%左右，LAMR在50%左右】
![1678534250474](https://user-images.githubusercontent.com/119500043/224481885-5e35773a-fe15-41d4-afc3-38c93eb8d0d3.png)

**Comment by Ye-zixiao** [comment]
没那么差的，而且默认的参数只是一些示例，你可以改改，或者说你可以先试着把代码大致过一遍，反正你已经成功跑起来了。差不多知道我怎么做的到时候即使不用我的，你自己想实现别的时候也可以做个参考，然后改改顺便参考下别人的想法实验写文章差不多就行了。反正多试试吧，我现在已经没有这个资源也没有空给你复现，还要忙着写工作上的东西呢~

**Comment by QRvlS** [comment]
> 没那么差的，而且默认的参数只是一些示例，你可以改改，或者说你可以先试着把代码大致过一遍，反正你已经成功跑起来了。差不多知道我怎么做的到时候即使不用我的，你自己想实现别的时候也可以做个参考，然后改改顺便参考下别人的想法实验写文章差不多就行了。反正多试试吧，我现在已经没有这个资源也没有空给你复现，还要忙着写工作上的东西呢~

谢谢大大！我再试试吧，从您的工程里学到了很多东西！谢谢谢谢！
